### ISSUE TITLE
Alter the generic Logentries script to rightscale standards

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/Rightscript-Logentries#1]
http://support.rightscale.com/27-Partners
A Manual install would look like this.

swap any `apt-get install logentries-daemon` with dpkg of an attached installer.

> Define a list of logs to monitor via inputs
le follow PATH_TO_LOG_FILE
le register --account-key=YOUR_ACCOUNT_KEY
apt-get install logentries-daemon
le follow PATH_TO_LOG_FILE (Repeat this step for each log file you wish to follow)
sudo service logentries restart

**Comment by therealx** [comment]
This has been done for a long time.
